### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by rducic** [agconti/KaggleAux#1]
How do I install and reference this package ?
I have cloned it on my desktop but how do I reference it ?

I tried adding it 
import sys
sys.path.append('/Users/user/Documents/KaggleAux/kaggleaux')

But I still get an error when I run :+1: 
from KaggleAux import predict as ka # see github.com/agconti/kaggleaux for more details

No module named KaggleAux

**Comment by agconti** [comment]
Hi @talenyc,

Thanks for opening up an issue. Are you running this command from the kaggle-titanic tutorial?

**Comment by rducic** [comment]
I am running this command from my ipython notebook and I'm following the kaggle-titanic tutorial.
As stated above I have cloned it to my desktop.

**Comment by agconti** [comment]
Hey @talenyc, You're on the right track with:

``` python
import sys
sys.path.append('/Users/user/Documents/KaggleAux/kaggleaux')
```

I'm not sure why it wouldn't be working; can you give me more information about the error you're getting? 

I keep a completely striped down version of KaggleAux in the titanic tutorial. So this issue is particular to that version, and not the one contained in this repository. Since it belongs there, I'll migrate this issue to the kaggle-titanic repo. I'm also going to make this package available through `pip install`, so these sorts of issues won't pop up in the future.

**Comment by agconti** [comment]
https://github.com/agconti/kaggle-titanic/issues/6

**Comment by agconti** [comment]
Also, #2.

**Comment by mbadrawy1** [comment]
Can you help me how did you predict your results without KaggleAux
